### ISSUE TITLE
Deadline Modifier

### ISSUE THREAD

**Issue by ZainMustafaaa** [HamzaYasin1/ERC20-token-fixed-supply#1]
Hi Hamza Yasin
You are using deadline modifier against almost every function but i really not seen this type of modifier in your repository.
https://github.com/HamzaYasin1/ERC20-token-fixed-supply/blob/4ff2cfb68f40043b9f6773bf96df5ce5ed795409/MyToken.sol#L64

**Comment by HamzaYasin1** [comment]
Hi ZainMustafaaa
i'm really sorry to see this stupid mistake you just ignore this modifier and use this code without using deadlineCheckPoint modifier.
Thanks for counting this silly mistake in my code.
Problem solved.

**Comment by ZainMustafaaa** [comment]
@HamzaYasin1 Please add this point to your README file to make other peoples understand easier.
Thank You
