### ISSUE TITLE
Ether Value

### ISSUE THREAD

**Issue by ZainMustafaaa** [HamzaYasin1/ERC20-token-fixed-supply#2]
Hi Hamza Yasin
Why are you taking _etherVal variable as parameter whether you are not using this any where
https://github.com/HamzaYasin1/ERC20-token-fixed-supply/blob/4ff2cfb68f40043b9f6773bf96df5ce5ed795409/MyToken.sol#L43

**Comment by HamzaYasin1** [comment]
Hi @ZainMustafaaa !
New commit of MyToken.sol is updated. All issues are clear maybe.
Thanks for your interest.
